### ISSUE TITLE
Suggestion - use logger/logging instead of print

### ISSUE THREAD

**Issue by kfigaj** [ashtree74/MeshData#1]
https://github.com/ashtree74/MeshData/blob/73c7dbb765b86624fd49a95bdcbd0382d67effe1/main.py#L30

Please see reason and example here:
https://www.digitalocean.com/community/tutorials/how-to-use-logging-in-python-3

**Comment by ashtree74** [comment]
I'll implement it. Thx.

**Comment by ashtree74** [comment]
Done.
