### ISSUE TITLE
Write unit tests

### ISSUE THREAD

**Issue by kfigaj** [ashtree74/MeshData#2]
https://github.com/ashtree74/MeshData/blob/73c7dbb765b86624fd49a95bdcbd0382d67effe1/main.py#L9

Unit test will give you base for automatic, repeatable verification of logic in your code.
Additionally, they will be must have  during code changes.

Please see examples below: 

https://docs.python.org/3/library/unittest.html

**Comment by ashtree74** [comment]
Amazing. I never did it - very useful thing.

**Comment by ashtree74** [comment]
Done
