### ISSUE TITLE
What will happen here if file loading in __init__ will not work?

### ISSUE THREAD

**Issue by kfigaj** [ashtree74/MeshData#5]
https://github.com/ashtree74/MeshData/blob/73c7dbb765b86624fd49a95bdcbd0382d67effe1/main.py#L60

Objects, classes are just abstract representations of concepts. Their methods should have one, clear and separated responsibility. It is easier to test this way :)
DataStream might be responsible here for data reading, parsing, and keeping it in some variable. 

Let it have methods as now one for loading, one for parsing, one for getting data. Avoid calling one from another. There is a clear logic flow here - do it in another method.

**Comment by ashtree74** [comment]
Done. Could you check it? Is it better?
